r"""Emit src/game/errors_table.h: every eErr* name with the global that holds
its hash at runtime.

The values themselves are never in the file. A2 (Flight Freedom) established
that each name's numeric value is written once at process start into a private
global, and that the global is the one loaded 0x1C bytes before the lea that
points at the name. This applies that derivation to every eErr name in the
image, drops the ones that are ambiguous, and writes the pairs out. The probe
reads the globals at startup and builds value -> name from them, so a wrong
table shows up as zeros rather than as wrong names.

    py -3 research\gen_errors.py

Re-run it after a game update: the RVAs move, the names do not.
"""
import os
import re
import struct
import sys

sys.path.insert(0, r"C:\working\cd mods\No more flight restrictions\private\research")
from cdimage import load_image, sections

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "mod", "src", "game", "errors_table.h")
BUILD = "2.03.00 / exe 1.0.0.2944"


def main():
    base, img, pe = load_image()
    imgb = bytes(img)
    sec = sections(pe)

    def sec_of(r):
        for n, (a, b) in sec.items():
            if a <= r < b:
                return n
        return "?"

    names = {}
    for m in re.finditer(rb'eErr[A-Za-z0-9_]{3,70}\x00', imgb):
        i = m.start()
        if i and imgb[i - 1] != 0:
            continue
        names[i] = m.group()[:-1].decode()

    leas = {}
    for m in re.finditer(rb'[\x40-\x4f]\x8d[\x05\x0d\x15\x1d\x25\x2d\x35\x3d]', imgb):
        i = m.start()
        d = struct.unpack_from('<i', imgb, i + 3)[0]
        leas.setdefault(i + 7 + d, []).append(i)

    # name -> the set of globals derived from every lea that points at it
    n2g = {}
    for sr, nm in names.items():
        for r in leas.get(sr, []):
            zl = r - 0x1C
            if imgb[zl + 1] != 0x8d or not (0x40 <= imgb[zl] <= 0x4f):
                continue
            d = struct.unpack_from('<i', imgb, zl + 3)[0]
            g = zl + 7 + d
            if sec_of(g) in (".sbss", ".debug$P"):
                n2g.setdefault(nm, set()).add(g)

    rows, dropped_multi = [], 0
    for nm, gs in n2g.items():
        if len(gs) != 1:
            dropped_multi += 1
            continue
        rows.append((nm, next(iter(gs))))

    # A global claimed by more than one name cannot be attributed, so drop all
    # of its claimants rather than pick one.
    byg = {}
    for nm, g in rows:
        byg.setdefault(g, []).append(nm)
    kept = sorted((nm, g) for g, ns in byg.items() if len(ns) == 1 for nm in ns)
    dropped_shared = len(rows) - len(kept)

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by research/gen_errors.py. Do not edit.\n")
        f.write(f"// Game build {BUILD}. {len(names)} eErr names in the image, "
                f"{len(kept)} with an unambiguous global.\n")
        f.write(f"// Dropped: {dropped_multi} whose leas disagree, {dropped_shared} sharing a global.\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write("namespace bp::errors_table\n{\n")
        f.write("    struct Entry { uint32_t rva; const char* name; };\n")
        f.write(f"    inline constexpr const char* kBuild = \"{BUILD}\";\n")
        f.write("    inline constexpr Entry kEntries[] = {\n")
        for nm, g in kept:
            f.write(f"        {{ 0x{g:X}u, \"{nm}\" }},\n")
        f.write("    };\n")
        f.write("    inline constexpr int kCount = static_cast<int>(sizeof(kEntries) / sizeof(kEntries[0]));\n")
        f.write("}\n")

    print(f"names {len(names)}, derived {len(n2g)}, written {len(kept)}")
    print(f"dropped: {dropped_multi} ambiguous lea, {dropped_shared} shared global")
    print("->", OUT)
    for probe in ("eErrNoFieldMoveHolding", "eErrNoInvalidField", "eErrNoCantDoWhileCatchingOrCatched"):
        hit = [g for nm, g in kept if nm == probe]
        print(f"   {probe}: {'+0x%X' % hit[0] if hit else 'NOT IN TABLE'}")


if __name__ == "__main__":
    main()
